/* ========== CONSTRAINTS ========== */

ALTER TABLE TRANSLATION_ENTRY
  DROP PRIMARY KEY,
  DROP FOREIGN KEY FK_TRE_ID_TRN_ID,
  DROP FOREIGN KEY FK_TRE_ID_LAN_CODE;

ALTER TABLE COUNTRY_CODE
  DROP FOREIGN KEY FK_CCD_DESC;

ALTER TABLE CURRENCY_CODE
  DROP FOREIGN KEY FK_CUR_DESC;

ALTER TABLE RESTAURANTS
  DROP FOREIGN KEY FK_RST_LOCALE,
  DROP FOREIGN KEY FK_RST_COUNTRY,
  DROP FOREIGN KEY FK_RST_CURRENCY;
DROP INDEX IDX_RST_LOGIN
ON RESTAURANTS;
DROP INDEX IDX_RST_NAME
ON RESTAURANTS;
DROP INDEX IDX_RST_LAT
ON RESTAURANTS;
DROP INDEX IDX_RST_LONG
ON RESTAURANTS;
DROP INDEX IDX_RST_CITY
ON RESTAURANTS;

ALTER TABLE RESTAURANTS_CONTACT_INFO
  DROP FOREIGN KEY FK_RSC_RST_ID;

ALTER TABLE RESTAURANTS_LEGAL_INFO
  DROP FOREIGN KEY FK_RSL_RST_ID,
  DROP FOREIGN KEY FK_RSL_LEGAL_COUNTRY,
  DROP FOREIGN KEY FK_RSL_PROFILE_TYPE;
DROP INDEX IDX_RSL_LEGAL_NAME
ON RESTAURANTS_LEGAL_INFO;
DROP INDEX IDX_RSL_LEGAL_VAT
ON RESTAURANTS_LEGAL_INFO;

ALTER TABLE MENUS
  DROP FOREIGN KEY FK_MNU_TITLE;
DROP INDEX IDX_MNU_RST_ID_ORDER_ID
ON MENUS;

ALTER TABLE MENU_ITEMS
  DROP FOREIGN KEY FK_MNU_ITM_TITLE,
  DROP FOREIGN KEY FK_MNU_ITM_DESC,
  DROP FOREIGN KEY FK_MNU_ITM_TYPE;
DROP INDEX IDX_MNU_ITM
ON MENU_ITEMS;
DROP INDEX IDX_MNU_ITM_TITLE
ON MENU_ITEMS;

ALTER TABLE INGREDIENTS
  DROP FOREIGN KEY FK_ING_NAME;

ALTER TABLE MENU_ITEMS_INGREDIENTS
  DROP PRIMARY KEY;

ALTER TABLE MENU_ITEMS_TAGS
  DROP PRIMARY KEY,
  DROP FOREIGN KEY FK_TAG_ITM_ID,
  DROP FOREIGN KEY FK_TAG_CODE;

ALTER TABLE MENU_ITEMS_COMMENTS
  DROP FOREIGN KEY FK_COM_ITM_ID;

ALTER TABLE USERS
  DROP FOREIGN KEY FK_USR_PROFILE_TYPE,
  DROP FOREIGN KEY FK_USR_FAV_LAN_CODE;
DROP INDEX IDX_USR_LOGIN
ON USERS;

ALTER TABLE ORDERS
  DROP FOREIGN KEY FK_ORD_RST_ID,
  DROP FOREIGN KEY FK_ORD_USR_ID,
  DROP FOREIGN KEY FK_ORD_STATUS,
  DROP FOREIGN KEY FK_ORD_PAY_MODE;

ALTER TABLE ORDER_ITEMS
  DROP PRIMARY KEY,
  DROP FOREIGN KEY FK_ORI_ORD_ID,
  DROP FOREIGN KEY FK_ORI_USR_ID;

/* ========== INTERNATIONALIZATION ========== */

DROP TABLE IF EXISTS LANGUAGE_CODE;

DROP TABLE IF EXISTS TRANSLATION;

DROP TABLE IF EXISTS TRANSLATION_ENTRY;

DROP TABLE IF EXISTS COUNTRY_CODE;

DROP TABLE IF EXISTS CURRENCY_CODE;

/* ========== RESTAURANTS ========== */

DROP TABLE IF EXISTS RESTAURANTS;

DROP TABLE IF EXISTS RESTAURANTS_CONTACT_INFO;

DROP TABLE IF EXISTS RESTAURANTS_LEGAL_INFO;

DROP TABLE IF EXISTS RESTAURANT_PROFILE_TYPE;

/* ========== MENUS ========== */

DROP TABLE IF EXISTS CONFIGURATION;

DROP TABLE IF EXISTS MENU_ITEM_TYPE;

DROP TABLE IF EXISTS MENUS;

DROP TABLE IF EXISTS MENU_ITEMS;

DROP TABLE IF EXISTS INGREDIENTS;

DROP TABLE IF EXISTS MENU_ITEMS_INGREDIENTS;

DROP TABLE IF EXISTS TAGS;

DROP TABLE IF EXISTS MENU_ITEMS_TAGS;

DROP TABLE IF EXISTS MENU_ITEMS_COMMENTS;

/* ========== USERS ========== */

DROP TABLE IF EXISTS USER_PROFILE_TYPE;

DROP TABLE IF EXISTS USERS;

/* ========== ORDERS ========== */

DROP TABLE IF EXISTS ORDER_STATUS;

DROP TABLE IF EXISTS ORDER_PAY_MODE;

DROP TABLE IF EXISTS ORDERS;

DROP TABLE IF EXISTS ORDER_ITEMS;